config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tokens
  devise_for :auth_users, controllers: {
    sessions: 'auth_users/sessions',
    registrations: 'auth_users/registrations'
  }
  root 'pages#index'
  get '/link', to: 'pages#link'
  post '/link', to: 'pages#link_kiosk', as: :user_kiosks

  get '/kiosks', to: 'pages#kiosks'

  namespace :api do
    namespace :v1 do
      resources :kiosk, only: [:new] do
        member do
          get 'videos'
        end
      end
      resources :user, only: [] do
        collection do
          get 'kiosks'
        end
      end
      resources :auth_user, only: [] do
        collection do
          post 'register'
        end
      end
    end
  end

  namespace :admin do
    resources :shows
    resources :episodes
    resources :segments
    resources :playlists
    resources :playlist_playables
  end

  resources :kiosk, only: %i[index show] do
    collection do
      get :link
      post :link, to: 'pages#link_kiosk', as: :link_kiosk
    end
    member do
      get :authenticate
    end
  end
  namespace :kiosk do
    %i[shows episodes segments].each do |playable|
      resources playable, only: [] do
        member do
          get :play
        end
      end
    end
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/playables/playlist.rb
class Playlist < ApplicationRecord
  include Playable

  has_many :playlist_playables
  has_many :playables, through: :playlist_playables

  def resolve
    self.ordered_playables.map { |playable| playable.resolve }.flatten
  end

  def ordered_playables
    self.playlist_playables.order(:order)
  end
end

app/controllers/admin/playlists_controller.rb
module Admin
  class PlaylistsController < ApplicationController
    before_action :set_playlist, only: [:show, :edit, :update, :destroy]

    # GET /playlists
    # GET /playlists.json
    def index
      @playlists = Playlist.all
    end

    # GET /playlists/1
    # GET /playlists/1.json
    def show
    end

    # GET /playlists/new
    def new
      @playlist = Playlist.new
    end

    # GET /playlists/1/edit
    def edit
    end

    # POST /playlists
    # POST /playlists.json
    def create
      @playlist = Playlist.new(playlist_params)

      respond_to do |format|
        if @playlist.save
          format.html { redirect_to [:admin, @playlist], notice: 'Playlist was successfully created.' }
          format.json { render :show, status: :created, location: @playlist }
        else
          format.html { render :new }
          format.json { render json: @playlist.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /playlists/1
    # PATCH/PUT /playlists/1.json
    def update
      respond_to do |format|
        if @playlist.update(playlist_params)
          format.html { redirect_to [:admin, @playlist], notice: 'Playlist was successfully updated.' }
          format.json { render :show, status: :ok, location: @playlist }
        else
          format.html { render :edit }
          format.json { render json: @playlist.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /playlists/1
    # DELETE /playlists/1.json
    def destroy
      @playlist.destroy
      respond_to do |format|
        format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_playlist
        @playlist = Playlist.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def playlist_params
        params.require(:playlist).permit(:name)
      end
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/admin/playlists/_form.html.erb
<%= form_with(model: [:admin, playlist], local: true) do |form| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', [:admin, @playlist] %> |
<%= link_to 'Back', admin_playlists_path %>

app/views/admin/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Playlists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= link_to 'Show', [:admin, playlist] %></td>
        <td><%= link_to 'Edit', edit_admin_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', [:admin, playlist], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_admin_playlist_path %>

app/views/admin/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', admin_playlists_path %>

app/views/admin/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<%= link_to 'Edit', edit_admin_playlist_path(@playlist) %> |
<%= link_to 'Back', admin_playlists_path %>