config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tokens
  devise_for :auth_users, controllers: {
    sessions: 'auth_users/sessions',
    registrations: 'auth_users/registrations'
  }
  root 'pages#index'
  get '/link', to: 'pages#link'
  post '/link', to: 'pages#link_kiosk', as: :user_kiosks

  get '/kiosks', to: 'pages#kiosks'

  namespace :api do
    namespace :v1 do
      resources :kiosk, only: [:new] do
        member do
          get 'videos'
        end
      end
      resources :user, only: [] do
        collection do
          get 'kiosks'
        end
      end
      resources :auth_user, only: [] do
        collection do
          post 'register'
        end
      end
    end
  end

  namespace :admin do
    resources :shows
    resources :episodes
    resources :segments
    resources :playlists
    resources :playlist_playables
  end

  resources :kiosk, only: %i[index show] do
    collection do
      get :link
      post :link, to: 'pages#link_kiosk', as: :link_kiosk
    end
    member do
      get :authenticate
    end
  end
  namespace :kiosk do
    %i[shows episodes segments].each do |playable|
      resources playable, only: [] do
        member do
          get :play
        end
      end
    end
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/token.rb
# frozen_string_literal: true

class Token < ApplicationRecord
  belongs_to :auth_user

  validates :token, presence: true

  scope :active, -> { where('deleted = false') }

  scope :deleted, -> { where('deleted = true') }

  def make_token
    self.token = JsonToken.encode({ auth_user_id: auth_user_id })
    self
  end

  def to_s
    name
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: [:show, :edit, :update, :destroy]

  # GET /tokens
  # GET /tokens.json
  def index
    @tokens = Token.all
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
  end

  # GET /tokens/new
  def new
    @token = Token.new
  end

  # GET /tokens/1/edit
  def edit
  end

  # POST /tokens
  # POST /tokens.json
  def create
    @token = Token.new(token_params)

    respond_to do |format|
      if @token.save
        format.html { redirect_to @token, notice: 'Token was successfully created.' }
        format.json { render :show, status: :created, location: @token }
      else
        format.html { render :new }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokens/1
  # PATCH/PUT /tokens/1.json
  def update
    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to @token, notice: 'Token was successfully updated.' }
        format.json { render :show, status: :ok, location: @token }
      else
        format.html { render :edit }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token.destroy
    respond_to do |format|
      format.html { redirect_to tokens_url, notice: 'Token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_token
      @token = Token.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def token_params
      params.require(:token).permit(:name, :token, :deleted, :auth_user_id)
    end
end

app/views/tokens/_form.html.erb
<%= form_with(model: token, local: true) do |form| %>
  <% if token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
        <% token.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <div class="field">
    <%= form.label :deleted %>
    <%= form.check_box :deleted %>
  </div>

  <div class="field">
    <%= form.label :auth_user_id %>
    <%= form.text_field :auth_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tokens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Token</th>
      <th>Deleted</th>
      <th>Auth user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.name %></td>
        <td><%= token.token %></td>
        <td><%= token.deleted %></td>
        <td><%= token.auth_user_id %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_token_path(token) %></td>
        <td><%= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token', new_token_path %>

app/views/tokens/new.html.erb
<h1>New Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @token.name %>
</p>

<p>
  <strong>Token:</strong>
  <%= @token.token %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @token.deleted %>
</p>

<p>
  <strong>Auth user:</strong>
  <%= @token.auth_user_id %>
</p>

<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>