config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tokens
  devise_for :auth_users, controllers: {
    sessions: 'auth_users/sessions',
    registrations: 'auth_users/registrations'
  }
  root 'pages#index'
  get '/link', to: 'pages#link'
  post '/link', to: 'pages#link_kiosk', as: :user_kiosks

  get '/kiosks', to: 'pages#kiosks'

  namespace :api do
    namespace :v1 do
      resources :kiosk, only: [:new] do
        member do
          get 'videos'
        end
      end
      resources :user, only: [] do
        collection do
          get 'kiosks'
        end
      end
      resources :auth_user, only: [] do
        collection do
          post 'register'
        end
      end
    end
  end

  namespace :admin do
    resources :shows
    resources :episodes
    resources :segments
    resources :playlists
    resources :playlist_playables
  end

  resources :kiosk, only: %i[index show] do
    collection do
      get :link
      post :link, to: 'pages#link_kiosk', as: :link_kiosk
    end
    member do
      get :authenticate
    end
  end
  namespace :kiosk do
    %i[shows episodes segments].each do |playable|
      resources playable, only: [] do
        member do
          get :play
        end
      end
    end
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/playables/show.rb
class Show < ApplicationRecord
  include Playable
  has_many :episodes

  def resolve
    self.episodes.map { |episode| episode.resolve }.flatten
  end
end

app/controllers/admin/shows_controller.rb
module Admin
  class ShowsController < ApplicationController
    before_action :set_show, only: [:show, :edit, :update, :destroy]

    # GET /shows
    # GET /shows.json
    def index
      @shows = Show.all
    end

    # GET /shows/1
    # GET /shows/1.json
    def show
    end

    # GET /shows/new
    def new
      @show = Show.new
    end

    # GET /shows/1/edit
    def edit
    end

    # POST /shows
    # POST /shows.json
    def create
      @show = Show.new(show_params)

      respond_to do |format|
        if @show.save
          format.html { redirect_to [:admin, @show], notice: 'Show was successfully created.' }
          format.json { render :show, status: :created, location: @show }
        else
          format.html { render :new }
          format.json { render json: @show.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /shows/1
    # PATCH/PUT /shows/1.json
    def update
      respond_to do |format|
        if @show.update(show_params)
          format.html { redirect_to [:admin, @show], notice: 'Show was successfully updated.' }
          format.json { render :show, status: :ok, location: @show }
        else
          format.html { render :edit }
          format.json { render json: @show.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /shows/1
    # DELETE /shows/1.json
    def destroy
      @show.destroy
      respond_to do |format|
        format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_show
        @show = Show.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def show_params
        params.require(:show).permit(:title)
      end
  end
end

app/controllers/kiosk/shows_controller.rb
  class Kiosk::ShowsController < KioskController
    def play
      @videos = show.resolve
    end

    private
    def show
      @show ||= Show.find(params[:id])
    end
  end

app/controllers/playable/shows_controller.rb
module Playable
  class ShowsController < PlayableController
    def play
      @videos = show.episodes.map{ |ep| ep.resolve.map { |segment| { id: segment.id, file: url_for(segment.video) } } }.flatten 
    end

    private
    def show
      @show ||= Show.find(params[:id])
    end
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/admin/shows/_form.html.erb
<%= form_with(model: [:admin, show], local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', [:admin, @show] %> |
<%= link_to 'Back', admin_shows_path %>

app/views/admin/shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shows</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= show.title %></td>
        <td><%= link_to 'Show', [:admin, show] %></td>
        <td><%= link_to 'Edit', edit_admin_show_path(show) %></td>
        <td><%= link_to 'Destroy', [:admin, show], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show', new_admin_show_path %>

app/views/admin/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', admin_shows_path %>

app/views/admin/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @show.title %>
</p>

<p>
  <strong>Episodes:</strong>
  <ul>
  <% @show.episodes.each do |episode| %>
    <li><%= link_to episode.title, admin_episode_path(episode) %> : <%= link_to 'Edit', edit_admin_episode_path(episode) %></li>
  <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_admin_show_path(@show) %> |
<%= link_to 'Back', admin_shows_path %>