config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tokens
  devise_for :auth_users, controllers: {
    sessions: 'auth_users/sessions',
    registrations: 'auth_users/registrations'
  }
  root 'pages#index'
  get '/link', to: 'pages#link'
  post '/link', to: 'pages#link_kiosk', as: :user_kiosks

  get '/kiosks', to: 'pages#kiosks'

  namespace :api do
    namespace :v1 do
      resources :kiosk, only: [:new] do
        member do
          get 'videos'
        end
      end
      resources :user, only: [] do
        collection do
          get 'kiosks'
        end
      end
      resources :auth_user, only: [] do
        collection do
          post 'register'
        end
      end
    end
  end

  namespace :admin do
    resources :shows
    resources :episodes
    resources :segments
    resources :playlists
    resources :playlist_playables
  end

  resources :kiosk, only: %i[index show] do
    collection do
      get :link
      post :link, to: 'pages#link_kiosk', as: :link_kiosk
    end
    member do
      get :authenticate
    end
  end
  namespace :kiosk do
    %i[shows episodes segments].each do |playable|
      resources playable, only: [] do
        member do
          get :play
        end
      end
    end
  end

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/playables/segment.rb
class Segment < ApplicationRecord
  include Playable

  has_many :episodes, through: :episode_segments
  has_one_attached :video

  def resolve
    { id: id, file: Rails.application.routes.url_helpers.url_for(video) }
  end
end

app/controllers/admin/segments_controller.rb
module Admin
  class SegmentsController < ApplicationController
    before_action :set_segment, only: [:show, :edit, :update, :destroy]

    # GET /segments
    # GET /segments.json
    def index
      @segments = Segment.all
    end

    # GET /segments/1
    # GET /segments/1.json
    def show
    end

    # GET /segments/new
    def new
      @segment = Segment.new
    end

    # GET /segments/1/edit
    def edit
    end

    # POST /segments
    # POST /segments.json
    def create
      @segment = Segment.new(segment_params)
      @segment.video.attach(params[:segment][:video])

      respond_to do |format|
        if @segment.save
          format.html { redirect_to [:admin, @segment], notice: 'Segment was successfully created.' }
          format.json { render :show, status: :created, location: @segment }
        else
          format.html { render :new }
          format.json { render json: @segment.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /segments/1
    # PATCH/PUT /segments/1.json
    def update
      respond_to do |format| 
      if @segment.update(segment_params) && @segment.video.attach(params[:segment][:video])
          format.html { redirect_to [:admin, @segment], notice: 'Segment was successfully updated.' }
          format.json { render :show, status: :ok, location: @segment }
        else
          format.html { render :edit }
          format.json { render json: @segment.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /segments/1
    # DELETE /segments/1.json
    def destroy
      @segment.destroy
      respond_to do |format|
        format.html { redirect_to segment_url, notice: 'Segment was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_segment
        @segment = Segment.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def segment_params
        params.require(:segment).permit(:title)
      end
  end
end

app/controllers/kiosk/segments_controller.rb
class Kiosk::SegmentsController < KioskController
  def play
    @videos = segment.resolve
  end

  private
  def segment
    @segment ||= Segment.find(params[:id])
end

app/controllers/playable/segments_controller.rb
module Playable
  class SegmentsController < PlayableController
    def play
      @videos = [Segment.first.video]
    end
  end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/admin/segments/_form.html.erb
<%= form_with(model: [:admin, segment], local: true) do |form| %>
  <% if segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
        <% segment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
<%#
  <div class="field">
    <%= form.label :episode 
    <%= form.hidden_field :episode_id 

    <% episode_name = segment.episode.present? ? segment.episode.title : "Search Episodes..." 
    <%= text_field_tag 'episode_name', nil, placeholder: episode_name  
    <div class="selection"></div>
    <div id="autoComplete_list"></div>
  </div>
%>

  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/segments/edit.html.erb
<h1>Editing Segment</h1>

<%= render 'form', segment: @segment %>

<%= link_to 'Show', [:admin, @segment] %> |
<%= link_to 'Back', admin_shows_path %>

app/views/admin/segments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Segments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.title %></td>
        <td><%= link_to 'Show', [:admin, segment] %></td>
        <td><%= link_to 'Edit', edit_admin_segment_path(segment) %></td>
        <td><%= link_to 'Destroy', [:admin, segment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segment', new_admin_segment_path %>

app/views/admin/segments/new.html.erb
<h1>New Segment</h1>

<%= render 'form', segment: @segment %>

<%= link_to 'Back', admin_segments_path %>

app/views/admin/segments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @segment.title %>
</p>

<p>
  <strong>Video:</strong>
  <%= video_tag url_for(@segment.video) %>
</p>

<%= link_to 'Edit', edit_admin_segment_path(@segment) %> |
<%= link_to 'Back', admin_segments_path %>